nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app
mysql:
    image: mysql:latest
    volumes_from:
        - data
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret_pwd
        MYSQL_DATABASE: projet
        MYSQL_USER: project_user
        MYSQL_PASSWORD: project_pwd

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql

app:
    image: php:7.0-fpm
    volumes:
        - /home/docker/app:/var/www/html
    command: "true"
data:
    image: mysql:latest
    volumes:
        - /home/docker/mysql
    command: "true"
